mindmap
  root(modo)
  ::icon(fa fa-folder)
    sample
    ::icon(fa fa-folder)
        sample1
        ::icon(fa fa-folder)
            metadata
            ::icon(fa fa-diagram-project)
    assay
    ::icon(fa fa-folder)
        assay A
        ::icon(fa fa-folder)
            metadata
            ::icon(fa fa-diagram-project)
            array A
            ::icon(fa fa-database)
        assay B
        ::icon(fa fa-folder)
            metadata
            ::icon(fa fa-diagram-project)
            array B
            ::icon(fa fa-database)
    data
    ::icon(fa fa-folder)
        data1
            metadata
            ::icon(fa fa-diagram-project)
        data2
            metadata
            ::icon(fa fa-diagram-project)
    reference
    ::icon(fa fa-folder)
    sample1_genome.cram
    ::icon(fa fa-file)

