name: Main and PR pipeline

on:
  push:
    branches:
      - main

  workflow_call:

  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      is_release: false
